[database]
# 数据库位置
path = "anime.db"

[search]
# 搜索结果的相似程度
threshold = 75

[bangumi]
# 网络请求重试次数
try_times = 10
# 网络超时设置，单位为秒
timeout = 10
# 此项用于设置 User-Agent，请不要轻易改动
user_agent = "kao-chinaklp/BangumiFatch"